camid: 0

sample:
  from: 1
  to: 30

data_path: ./data

crop: True

marker:
  x0_: 10 #/ RESCALE
  y0_: 17 #/ RESCALE
  dx_: 40 #/ RESCALE
  dy_: 40 #/ RESCALE
  N_: 5
  M_: 5

calibration:
  upleft_x: 170
  upleft_y: 83
  downright_x: 434
  downright_y: 318
  method: camera # marker or camera
  BallRad: 3 #4.76/2 #mm
  Pixmm: 0.031067    #.10577 #4.76/100 #0.0806 * 1.5 mm/pixel # 0.03298 = 3.40 / 103.0776
  ratio: 0.5
  red_range: [-80, 90]  # [-45, 45]
  green_range: [-90, 90] #[-60, 50]
  blue_range: [-90, 90] # [-80, 60]
  zeropoint: [-90, -90, -90] 
  lookscale: [180., 180., 180.]

heightmap:
  cpp_enable: False
  abe_path: ./abe_corr.npz
  table_path: ./table.npy
  table_account_path: ./count_map.py
  table_smooth_path: ./table_smooth.npy

tracking:
  lib_path: ./lib
  RESCALE: 1
  fps_: 30
